version: '2'

services:

    mysql:
        image: mysql:5.7
        container_name: "mysql1"
        ports:
            - "3307:3306"
        volumes:
             - ./mysql/data1:/var/lib/mysql
             - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=123456

    mysql2:
        image: mysql:5.7
        container_name: "mysql2"
        ports:
            - "3308:3306"
        volumes:
             - ./mysql/data2:/var/lib/mysql
             - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=123456
