version: '2'

services:

    mysql:
        image: mysql:5.7
        container_name: "mysql"
        ports:
            - "3306:3306"
        volumes:
             - /mysql/data:/var/lib/mysql
             - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=123456

